### ISSUE TITLE
URL is not defined

### ISSUE THREAD

**Issue by felix-berlin** [mirkoschubert/gdpr-check#1]
Hi,
Wenn ich eine Seite scannen möchte bekomme ich jedesmal:

> Checking the URL ...
> URL is not defined

Die Seiten die ich scanne gibt es natürlich.

**Comment by mc-dee** [comment]
Hallo,
ich auch :(

Bei mir das gleiche (aktuelle Node.js für Windows)

**Comment by ludwig-schmidt** [comment]
bei mir auch das gleiche...

**Comment by mc-dee** [comment]
https://nodejs.org/en/download/current/ 
ich habe mir jetzt die version 10.2.1 gezogen in 32bit
nochmal per npm mit cmd im admin modus installier und ausgeführt, nun gehts

**Comment by mirkoschubert** [comment]
Bitte mal die auf aktuelle Version 0.3.2 aktualisieren ;) Ich hab den Fehler schon behoben.
Lag daran, dass die URL-Klasse erst ab der Node-Version 10 global läuft und ich für die älteren Versionen vergessen habe, das URL-Modul zu laden. Sorry für die Umstände!
