### ISSUE TITLE
Not detecting google analytics -- "Simple Google Analytics" WP plugin

### ISSUE THREAD

**Issue by jason-dd** [mirkoschubert/gdpr-check#10]
**Describe the bug**

Scanning sites utilizing the Simple Google Analytics plugin return - No Analytics Tool has been found.
Reproduced on multiple sites
Below is the code with the analytics at the bottom of the page

> </div>
> --
>   | <script type="text/javascript">panopress.imagebox();</script>
>   | 
>   | <script type="text/javascript">
>   | var _gaq = _gaq \|\| [];
>   | _gaq.push(['_setAccount','UA-123456-7']);
>   | _gaq.push(['_trackPageview']);
>   | (function() {
>   | var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
>   | ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
>   | var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
>   | })();
>   | </script>
>   | 
>   | <script type='text/javascript' src='http://www.site.com/wp-includes/js/wp-embed.min.js?ver=4.9.6'></script>
>   | </body>

Plugin; https://wordpress.org/plugins/simple-google-analytics/

**Comment by DanielRuf** [comment]
Can you dump `window` on the browser console and check if there are any `ga` variables set?

**Comment by mirkoschubert** [comment]
@jason-dd Do you have an example URL for testing?

Problem is, that this plugin obviously uses the legacy API of Google Analytics (ga.js), which is deprecated (see [gajs](https://developers.google.com/analytics/devguides/collection/gajs/methods/)). I don't cover this for now.

But I'm working on it. I think I should show a deprecation warning for this case.

**Comment by mirkoschubert** [comment]
Btw, I wouldn't recommend using this plugin at all. If the screenshot is up-to-date (and the change log supports my theory), then this plugin doesn't support anonymiseIP or forceSSL which is definitely **not** GDPR compliant. 😏

**Comment by jason-dd** [comment]
URL to try is 1kwrds.com
I (personally) am not concerned with gdpr, was testing tool on different sites for curiosity.

**Comment by mirkoschubert** [comment]
@jason-dd It should be working now (at least in the `dev`branch). I merge it when the next version comes out.

**Comment by DanielRuf** [comment]
`npm i -g gdpr-cli@dev`
