### ISSUE TITLE
ideas, proposals (functional programming)

### ISSUE THREAD

**Issue by DanielRuf** [mirkoschubert/gdpr-check#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A more functional programming approach for better maintainability and readability.

**Describe alternatives you've considered**

Some ideas / modules which might be useful here:
https://github.com/DanielRuf/https-checks/blob/master/index.js
https://github.com/DanielRuf/symantecpkicerts/blob/master/index.js
https://github.com/DanielRuf/website-stack/blob/master/index.js
https://github.com/DanielRuf/website-checks/blob/master/index.js

**Additional context**

**Comment by Skyflash** [comment]
Isn't clear what is GDPR-ok and what is not.
I suppose the red sentences (ie: Google Fonts: 4) is not ok, but a little description may be better than a coloured number

**Comment by DanielRuf** [comment]
And solution proposals like https://google-webfonts-helper.herokuapp.com/fonts

**Comment by mirkoschubert** [comment]
@Skyflash As stated in the readme and the documentation, this tool will not provide any legal advice, it simply checks technical aspects, which might be relevant for the GDPR. In case of the fonts it shows Google Fonts and Adobe Typekit as well as locally installed fonts. The number only represents the number of found fonts, nothing more. 😏 Google Fonts could be a problem, but we only know for sure when the first verdicts arrive.
@DanielRuf I look into it tomorrow. For now, I'm going to bed 😄
