### ISSUE TITLE
Scan fails with SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by nohn** [mirkoschubert/gdpr-check#17]
**Describe the bug**
Scan fails with SyntaxError: Unexpected token ...

**To Reproduce**
1. sudo npm install -g gdpr-cli
2. gdpr scan www.example.com

**Expected behavior**
gdpr-cli scans www.example.com

**Desktop:**
 - OS: Ubuntu 16.04 LTS
 - Node Version v4.2.6

**Additional context**

Stacktrace:

`$ gdpr scan www.example.com
/usr/local/lib/node_modules/gdpr-cli/lib/ui.js:59
    cui.div(...data);
            ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gdpr-cli/lib/tasks.js:12:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
`

**Comment by DanielRuf** [comment]
Please try upgrading Node.js to 8 or 10.

**Comment by DanielRuf** [comment]
> sudo npm install -g gdpr-cli

Also please never use `sudo`.

**Comment by DanielRuf** [comment]
> SyntaxError: Unexpected token ...

This is the spread operator which was introduced in Node.js 8

**Comment by DanielRuf** [comment]
> SyntaxError: Unexpected token ...

This is the object rest / spread properties which was introduced in Node.js 8.3.
See https://stackoverflow.com/questions/40066731/node-v6-failing-on-object-spread and https://node.green/#ES2018-features-object-rest-spread-properties.

Also Node.js 4 is EOL since last month and should not be used anymore.

**Comment by nohn** [comment]
Thanks. Node 4 is the version that comes with Ubuntu 16.04:

`$ apt show nodejs
Package: nodejs
Version: 4.2.6~dfsg-1ubuntu4.1
`

**Comment by DanielRuf** [comment]
You can always use `nvm` for using multiple versions and switching them as needed.

**Comment by DanielRuf** [comment]
You can always use `nvm` for using multiple versions and switch them as needed.
