### ISSUE TITLE
proposal: puppeteer for more checks

### ISSUE THREAD

**Issue by DanielRuf** [mirkoschubert/gdpr-check#4]
I had the idea to create a similar tool but use puppeteer.

Puppeteer has a rich API for getting information about cookies, all requests, emulate languages, devices and much more.

**Comment by mirkoschubert** [comment]
I think, puppeteer would be a little bit of overkill, since it uses a copy of Chromium. But I'm gonna look into it, for sure ;)

**Comment by DanielRuf** [comment]
> I think, puppeteer would be a little bit of overkill, since it uses a copy of Chromium. But I'm gonna look into it, for sure ;)

You can tell Puppeteer to not download Chromium and use the installed Chrome instance ;-)
