### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by DanielRuf** [mirkoschubert/gdpr-check#5]
I saw that you mentioned my reserved package name ;-)

> Due to naming conventions in npmjs.com we changed our name from gdpr-check to gdpr-cli

Are still interested in using `gdpr-check`? I would be also interested in providing further checks, solutions and contribute to the project.

Unfortunately I did not get any email or contact request asking about the usage of `gdpr-check`. In general everyone can contact me and ask about unused package names and so on, I do not bite ;-)

**Comment by mirkoschubert** [comment]
@DanielRuf, there you are 😆 No, it wasn't any problem to rename my project and I think I won't switch back at the moment.
Nevertheless, you're welcome to contribute any time 😏
